# Google Cloud Build configuration for ConvoLab
# Builds monolithic container with client + server

steps:
  # Build combined image with cache busting
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'CACHE_BUST=${_CACHE_BUST}'
      - '-t'
      - '${_IMAGE_NAME}'
      - '.'

images:
  - '${_IMAGE_NAME}'

substitutions:
  _CACHE_BUST: 'default'
  _IMAGE_NAME: 'gcr.io/convolab-mvp/convolab'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
