const fs = require('fs');
const path = require('path');

// A2 Level - 1500 items (continuing from A1)
const a2Vocabulary = {
  "language": "fr",
  "level": "A2",
  "framework": "CEFR",
  "vocabulary": [
    // Continue with A2-appropriate vocabulary
    { "word": "accepter", "translation": "to accept", "partOfSpeech": "verb" },
    { "word": "accord", "translation": "agreement", "partOfSpeech": "noun" },
    { "word": "achats", "translation": "shopping, purchases", "partOfSpeech": "noun" },
    { "word": "activité", "translation": "activity", "partOfSpeech": "noun" },
    { "word": "addition", "translation": "bill, check", "partOfSpeech": "noun" },
    { "word": "adorer", "translation": "to adore", "partOfSpeech": "verb" },
    { "word": "adresse", "translation": "address", "partOfSpeech": "noun" },
    { "word": "affaires", "translation": "business, belongings", "partOfSpeech": "noun" },
    { "word": "affiche", "translation": "poster", "partOfSpeech": "noun" },
    { "word": "agence", "translation": "agency", "partOfSpeech": "noun" },
    { "word": "agent", "translation": "agent", "partOfSpeech": "noun" },
    { "word": "agréable", "translation": "pleasant", "partOfSpeech": "adjective" },
    { "word": "ailleurs", "translation": "elsewhere", "partOfSpeech": "adverb" },
    { "word": "ainsi", "translation": "thus, in this way", "partOfSpeech": "adverb" },
    { "word": "air", "translation": "air, appearance", "partOfSpeech": "noun" },
    { "word": "ajouter", "translation": "to add", "partOfSpeech": "verb" },
    { "word": "alcool", "translation": "alcohol", "partOfSpeech": "noun" },
    { "word": "allemand", "translation": "German", "partOfSpeech": "noun" },
    { "word": "Allemagne", "translation": "Germany", "partOfSpeech": "noun" },
    { "word": "allumer", "translation": "to turn on, light", "partOfSpeech": "verb" },
    { "word": "alors", "translation": "so, then", "partOfSpeech": "adverb" },
    { "word": "améliorer", "translation": "to improve", "partOfSpeech": "verb" },
    { "word": "amener", "translation": "to bring", "partOfSpeech": "verb" },
    { "word": "américain", "translation": "American", "partOfSpeech": "adjective" },
    { "word": "Amérique", "translation": "America", "partOfSpeech": "noun" },
    { "word": "amour", "translation": "love", "partOfSpeech": "noun" },
    { "word": "amusant", "translation": "amusing, fun", "partOfSpeech": "adjective" },
    { "word": "amuser", "translation": "to amuse", "partOfSpeech": "verb" },
    { "word": "ancien", "translation": "old, former", "partOfSpeech": "adjective" },
    { "word": "Angleterre", "translation": "England", "partOfSpeech": "noun" },
    { "word": "annoncer", "translation": "to announce", "partOfSpeech": "verb" },
    { "word": "annuaire", "translation": "directory, phone book", "partOfSpeech": "noun" },
    { "word": "annuel", "translation": "annual", "partOfSpeech": "adjective" },
    { "word": "annuler", "translation": "to cancel", "partOfSpeech": "verb" },
    { "word": "août", "translation": "August", "partOfSpeech": "noun" },
    { "word": "apercevoir", "translation": "to notice, perceive", "partOfSpeech": "verb" },
    { "word": "apparaître", "translation": "to appear", "partOfSpeech": "verb" },
    { "word": "appareil", "translation": "device, apparatus", "partOfSpeech": "noun" },
    { "word": "apparence", "translation": "appearance", "partOfSpeech": "noun" },
    { "word": "appartenir", "translation": "to belong", "partOfSpeech": "verb" },
    { "word": "application", "translation": "application", "partOfSpeech": "noun" },
    { "word": "appliquer", "translation": "to apply", "partOfSpeech": "verb" },
    { "word": "apporter", "translation": "to bring", "partOfSpeech": "verb" },
    { "word": "apprécier", "translation": "to appreciate", "partOfSpeech": "verb" },
    { "word": "approcher", "translation": "to approach", "partOfSpeech": "verb" },
    { "word": "après", "translation": "after", "partOfSpeech": "preposition" },
    { "word": "arbre", "translation": "tree", "partOfSpeech": "noun" },
    { "word": "architecte", "translation": "architect", "partOfSpeech": "noun" },
    { "word": "architecture", "translation": "architecture", "partOfSpeech": "noun" },
    { "word": "arranger", "translation": "to arrange", "partOfSpeech": "verb" },
    { "word": "arrêt", "translation": "stop", "partOfSpeech": "noun" },
    { "word": "arrêter", "translation": "to stop", "partOfSpeech": "verb" },
    { "word": "arrière", "translation": "back, rear", "partOfSpeech": "noun" },
    { "word": "article", "translation": "article", "partOfSpeech": "noun" },
    { "word": "artiste", "translation": "artist", "partOfSpeech": "noun" },
    { "word": "ascenseur", "translation": "elevator", "partOfSpeech": "noun" },
    { "word": "Asie", "translation": "Asia", "partOfSpeech": "noun" },
    { "word": "aspect", "translation": "aspect", "partOfSpeech": "noun" },
    { "word": "asseoir", "translation": "to sit down", "partOfSpeech": "verb" },
    { "word": "assister", "translation": "to attend, assist", "partOfSpeech": "verb" },
    { "word": "association", "translation": "association", "partOfSpeech": "noun" },
    { "word": "assurance", "translation": "insurance, assurance", "partOfSpeech": "noun" },
    { "word": "assurer", "translation": "to assure, insure", "partOfSpeech": "verb" },
    { "word": "atelier", "translation": "workshop", "partOfSpeech": "noun" },
    { "word": "atmosphère", "translation": "atmosphere", "partOfSpeech": "noun" },
    { "word": "attacher", "translation": "to attach, tie", "partOfSpeech": "verb" },
    { "word": "attaque", "translation": "attack", "partOfSpeech": "noun" },
    { "word": "attaquer", "translation": "to attack", "partOfSpeech": "verb" },
    { "word": "atteindre", "translation": "to reach, attain", "partOfSpeech": "verb" },
    { "word": "attention", "translation": "attention", "partOfSpeech": "noun" },
    { "word": "attirer", "translation": "to attract", "partOfSpeech": "verb" },
    { "word": "attitude", "translation": "attitude", "partOfSpeech": "noun" },
    { "word": "aucun", "translation": "no, none", "partOfSpeech": "adjective" },
    { "word": "augmenter", "translation": "to increase", "partOfSpeech": "verb" },
    { "word": "auprès", "translation": "near, with", "partOfSpeech": "preposition" },
    { "word": "auquel", "translation": "to which", "partOfSpeech": "pronoun" },
    { "word": "aussitôt", "translation": "immediately", "partOfSpeech": "adverb" },
    { "word": "autant", "translation": "as much, as many", "partOfSpeech": "adverb" },
    { "word": "auteur", "translation": "author", "partOfSpeech": "noun" },
    { "word": "autobus", "translation": "bus", "partOfSpeech": "noun" },
    { "word": "automne", "translation": "autumn", "partOfSpeech": "noun" },
    { "word": "automobile", "translation": "car", "partOfSpeech": "noun" },
    { "word": "autoriser", "translation": "to authorize", "partOfSpeech": "verb" },
    { "word": "autorité", "translation": "authority", "partOfSpeech": "noun" },
    { "word": "autoroute", "translation": "highway", "partOfSpeech": "noun" },
    { "word": "autour", "translation": "around", "partOfSpeech": "adverb" },
    { "word": "autrefois", "translation": "in the past", "partOfSpeech": "adverb" },
    { "word": "autrement", "translation": "otherwise", "partOfSpeech": "adverb" },
    { "word": "avance", "translation": "advance", "partOfSpeech": "noun" },
    { "word": "avancer", "translation": "to advance, move forward", "partOfSpeech": "verb" },
    { "word": "avant", "translation": "before", "partOfSpeech": "preposition" },
    { "word": "avantage", "translation": "advantage", "partOfSpeech": "noun" },
    { "word": "avec", "translation": "with", "partOfSpeech": "preposition" },
    { "word": "avenir", "translation": "future", "partOfSpeech": "noun" },
    { "word": "aventure", "translation": "adventure", "partOfSpeech": "noun" },
    { "word": "avenue", "translation": "avenue", "partOfSpeech": "noun" },
    { "word": "avertir", "translation": "to warn", "partOfSpeech": "verb" },
    { "word": "aviateur", "translation": "aviator, pilot", "partOfSpeech": "noun" },
    { "word": "avion", "translation": "airplane", "partOfSpeech": "noun" },
    { "word": "avis", "translation": "opinion, notice", "partOfSpeech": "noun" },
    { "word": "avocat", "translation": "lawyer, avocado", "partOfSpeech": "noun" },
    { "word": "avouer", "translation": "to admit, confess", "partOfSpeech": "verb" }
  ]
};

console.log('Generating A2 vocabulary file...');
console.log(`Current count: ${a2Vocabulary.vocabulary.length}`);
console.log('Note: This is a starter file. Full generation requires extensive vocabulary database.');
console.log('For production use, consider integrating with FLELex or similar CEFR-graded resources.');

const outputPath = path.join(__dirname, 'server/src/data/vocabulary/fr/A2.json');
fs.writeFileSync(outputPath, JSON.stringify(a2Vocabulary, null, 2));
console.log(`A2 vocabulary file written to: ${outputPath}`);
