import type { StudyReviewSessionActions } from './useStudyReviewSessionActions';
import type { StudyReviewSessionCore } from './useStudyReviewSessionCore';
import type { StudyReviewSessionInteractions } from './useStudyReviewSessionInteractions';
import type { StudyReviewSessionLifecycle } from './useStudyReviewSessionLifecycle';

const buildStudyReviewSessionResult = (
  core: StudyReviewSessionCore,
  interactions: StudyReviewSessionInteractions,
  actions: StudyReviewSessionActions,
  lifecycle: StudyReviewSessionLifecycle
) => ({
  focusMode: core.state.focusMode,
  sessionKind: core.state.sessionKind,
  lessonPhase: core.state.lessonPhase,
  cards: core.cards,
  masteryAnimation: core.state.masteryAnimation,
  sessionLoading: core.state.sessionLoading,
  sessionError: core.state.sessionError,
  reviewConflictRecovered: core.state.reviewConflictRecovered,
  currentCard: core.currentCard,
  revealed: core.state.revealed,
  editing: core.state.editing,
  showSetDueControls: core.state.showSetDueControls,
  undoPending: core.state.undoPending,
  reviewBusy: core.reviewBusy,
  reviewRetryAvailable: core.state.reviewRetryAvailable,
  sessionCounts: core.sessionCounts,
  sessionProgress: core.sessionProgress,
  sessionWrapUp: core.sessionWrapUp,
  reviewQueueExhausted: core.reviewQueueExhausted,
  reviewSessionComplete: core.reviewSessionComplete,
  achievementCompletion: core.state.achievementCompletion,
  achievementCatalog: core.achievementCatalog,
  achievementProgress: core.achievementProgress,
  achievementCompletionRefreshPending: core.state.achievementCompletionRefreshPending,
  currentAchievement: core.currentAchievement,
  currentAchievementIndex: core.state.currentAchievementIndex,
  completionAchievements: core.completionAchievements,
  practiceMode: core.practiceMode,
  practiceComplete: core.practiceComplete,
  motionPermissionState: lifecycle.motionPermissionState,
  promptAudioRef: interactions.promptAudioRef,
  answerAudioRef: interactions.answerAudioRef,
  reviewMutation: core.reviewMutation,
  cardActionMutation: core.cardActionMutation,
  updateCardMutation: core.updateCardMutation,
  deleteCardMutation: core.deleteCardMutation,
  regenerateAudioMutation: core.regenerateAudioMutation,
  updateCardErrorMessage: core.updateCardErrorMessage,
  setEditing: core.state.setEditing,
  setMasteryAnimation: core.state.setMasteryAnimation,
  setShowSetDueControls: core.state.setShowSetDueControls,
  revealCurrentCard: actions.revealCurrentCard,
  exitFocusMode: lifecycle.exitFocusMode,
  endReviewSession: lifecycle.endReviewSession,
  advanceAchievement: lifecycle.advanceAchievement,
  finishReviewSession: lifecycle.finishReviewSession,
  handleGrade: actions.handleGrade,
  retryPendingReview: actions.retryPendingReview,
  handleBuryForSession: actions.handleBuryForSession,
  handleCardAction: actions.handleCardAction,
  handleUndo: interactions.handleUndo,
  requestMotionPermission: lifecycle.requestMotionPermission,
  saveCurrentCard: actions.saveCurrentCard,
  deleteCurrentCard: actions.deleteCurrentCard,
  regenerateCurrentCardAudio: actions.regenerateCurrentCardAudio,
  enterFocusMode: lifecycle.enterFocusMode,
  beginLessonQuiz: lifecycle.beginLessonQuiz,
  loadNextLessonBatch: lifecycle.loadNextLessonBatch,
  startToughestPractice: lifecycle.startToughestPractice,
  exitPracticeMode: lifecycle.exitPracticeMode,
});

export default buildStudyReviewSessionResult;
