import { useCallback, useEffect, useRef, useState } from 'react';

import { generationApi } from '../lib/generationApi';
import type { Episode } from '../types';

const POLL_INTERVAL_MS = 1000;
const MAX_POLL_DURATION_MS = 5 * 60 * 1000;
const QUEUED_EPISODES_KEY = 'audio-generation-queued';

type ToastType = 'success' | 'error' | 'info';

interface AudioGenerationState {
  isGeneratingAudio: boolean;
  generationProgress: number;
  toastMessage: string | null;
  toastType: ToastType;
  generateAllSpeeds: () => Promise<void>;
  clearToast: () => void;
}

interface UsePlaybackAudioGenerationOptions {
  episodeId?: string;
  routeIdentity: string;
  episode: Episode | null;
  generateAllSpeedsAudio: (episodeId: string, dialogueId: string) => Promise<string>;
  loadEpisode: (bustCache?: boolean) => Promise<boolean>;
}

function readQueuedEpisodes(): string[] {
  const storedValue = sessionStorage.getItem(QUEUED_EPISODES_KEY);
  if (!storedValue) return [];

  try {
    const parsedValue: unknown = JSON.parse(storedValue);
    return Array.isArray(parsedValue)
      ? parsedValue.filter((value): value is string => typeof value === 'string')
      : [];
  } catch {
    sessionStorage.removeItem(QUEUED_EPISODES_KEY);
    return [];
  }
}

function recordQueuedEpisode(episodeId: string): void {
  const queuedEpisodes = readQueuedEpisodes();
  if (queuedEpisodes.includes(episodeId)) return;
  sessionStorage.setItem(QUEUED_EPISODES_KEY, JSON.stringify([...queuedEpisodes, episodeId]));
}

/** Owns the lifecycle of Playback's asynchronous multi-speed audio job. */
export default function usePlaybackAudioGeneration({
  episodeId,
  routeIdentity,
  episode,
  generateAllSpeedsAudio,
  loadEpisode,
}: UsePlaybackAudioGenerationOptions): AudioGenerationState {
  const [isGeneratingAudio, setIsGeneratingAudio] = useState(false);
  const [generationProgress, setGenerationProgress] = useState(0);
  const [toastMessage, setToastMessage] = useState<string | null>(null);
  const [toastType, setToastType] = useState<ToastType>('info');
  const pollingIntervalRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const pollingRequestRef = useRef<AbortController | null>(null);
  const pollInFlightRef = useRef(false);
  const runIdRef = useRef(0);
  const activeGenerationRouteRef = useRef<string | null>(null);
  const lastAutoGeneratedEpisodeRef = useRef<string | null>(null);

  const clearPolling = useCallback(() => {
    if (pollingIntervalRef.current) {
      clearInterval(pollingIntervalRef.current);
      pollingIntervalRef.current = null;
    }
    pollingRequestRef.current?.abort();
    pollingRequestRef.current = null;
    pollInFlightRef.current = false;
  }, []);

  const cancelActiveRun = useCallback(() => {
    runIdRef.current += 1;
    clearPolling();
  }, [clearPolling]);

  useEffect(() => {
    cancelActiveRun();
    activeGenerationRouteRef.current = null;
    setIsGeneratingAudio(false);
    setGenerationProgress(0);

    return cancelActiveRun;
  }, [cancelActiveRun, routeIdentity]);

  const generateAllSpeeds = useCallback(async () => {
    if (!episode?.dialogue || episode.id !== episodeId) return;
    if (activeGenerationRouteRef.current === routeIdentity) return;

    cancelActiveRun();
    activeGenerationRouteRef.current = routeIdentity;
    const runId = runIdRef.current;
    const isCurrentRun = () => runIdRef.current === runId;
    const releaseCurrentRun = () => {
      if (isCurrentRun()) activeGenerationRouteRef.current = null;
    };

    setIsGeneratingAudio(true);
    setGenerationProgress(0);

    try {
      const jobId = await generateAllSpeedsAudio(episode.id, episode.dialogue.id);
      recordQueuedEpisode(episode.id);
      if (!isCurrentRun()) return;
      const startTime = Date.now();

      const pollJob = async () => {
        if (!isCurrentRun() || pollInFlightRef.current) return;

        if (Date.now() - startTime > MAX_POLL_DURATION_MS) {
          clearPolling();
          releaseCurrentRun();
          setIsGeneratingAudio(false);
          setGenerationProgress(0);
          setToastMessage('Audio generation timed out. Please try again.');
          setToastType('error');
          return;
        }

        pollInFlightRef.current = true;
        const abortController = new AbortController();
        pollingRequestRef.current = abortController;

        try {
          const response = await fetch(generationApi.audio.job(jobId), {
            credentials: 'include',
            signal: abortController.signal,
          });
          if (!isCurrentRun()) return;
          if (!response.ok) throw new Error(`Audio job polling failed with ${response.status}`);

          const data: { progress?: unknown; state?: unknown } = await response.json();
          if (!isCurrentRun()) return;

          if (typeof data.progress === 'number' && Number.isFinite(data.progress)) {
            setGenerationProgress(Math.min(100, Math.max(0, data.progress)));
          }

          if (data.state === 'completed') {
            clearPolling();
            const didReload = await loadEpisode(true);
            if (!isCurrentRun()) return;
            releaseCurrentRun();
            setIsGeneratingAudio(false);
            setGenerationProgress(0);
            if (didReload) {
              setToastMessage('Audio generated successfully!');
              setToastType('success');
            } else {
              setToastMessage('Audio generated, but the episode could not be refreshed.');
              setToastType('error');
            }
          } else if (data.state === 'failed') {
            clearPolling();
            releaseCurrentRun();
            setIsGeneratingAudio(false);
            setGenerationProgress(0);
            setToastMessage('Failed to generate audio. Please try again.');
            setToastType('error');
          }
        } catch (error) {
          if (!isCurrentRun() || (error instanceof DOMException && error.name === 'AbortError')) {
            return;
          }
          console.error('Error polling job:', error);
          clearPolling();
          releaseCurrentRun();
          setIsGeneratingAudio(false);
          setGenerationProgress(0);
          setToastMessage('Failed to check generation status. Please refresh the page.');
          setToastType('error');
        } finally {
          if (runIdRef.current === runId) {
            pollInFlightRef.current = false;
            pollingRequestRef.current = null;
          }
        }
      };

      pollingIntervalRef.current = setInterval(pollJob, POLL_INTERVAL_MS);
    } catch (error) {
      if (!isCurrentRun()) return;
      console.error('Failed to start audio generation:', error);
      releaseCurrentRun();
      setIsGeneratingAudio(false);
      setGenerationProgress(0);
      setToastMessage('Failed to start audio generation. Please try again.');
      setToastType('error');
    }
  }, [
    cancelActiveRun,
    clearPolling,
    episode,
    episodeId,
    generateAllSpeedsAudio,
    loadEpisode,
    routeIdentity,
  ]);

  useEffect(() => {
    if (!episode?.dialogue || episode.id !== episodeId || episode.autoGenerateAudio === false) {
      return;
    }
    if (lastAutoGeneratedEpisodeRef.current === episode.id) return;

    const queuedEpisodes = readQueuedEpisodes();
    if (queuedEpisodes.includes(episode.id)) {
      lastAutoGeneratedEpisodeRef.current = episode.id;
      return;
    }

    const hasAllSpeeds = Boolean(
      episode.audioUrl_0_7 && episode.audioUrl_0_85 && episode.audioUrl_1_0
    );
    if (hasAllSpeeds || isGeneratingAudio) return;

    lastAutoGeneratedEpisodeRef.current = episode.id;
    generateAllSpeeds().catch(() => undefined);
  }, [episode, episodeId, generateAllSpeeds, isGeneratingAudio]);

  return {
    isGeneratingAudio,
    generationProgress,
    toastMessage,
    toastType,
    generateAllSpeeds,
    clearToast: () => setToastMessage(null),
  };
}
