import {
  STUDY_EXPORT_PAGE_SIZE_DEFAULT,
  STUDY_EXPORT_PAGE_SIZE_MAX,
} from '@languageflow/shared/src/studyConstants.js';

export const ANKI_DECK_NAME = '日本語';
export const FIELD_SEPARATOR = String.fromCharCode(31);
export const DEFAULT_STUDY_LIMIT = 20;
export const STUDY_MEDIA_SIGNED_URL_TTL_SECONDS = 5 * 60;
export const STUDY_MEDIA_SIGNED_URL_REFRESH_WINDOW_MS = 30 * 1000;
export const STUDY_MEDIA_REDIRECT_CACHE_MAX_ENTRIES = 1000;
export const STUDY_AUDIO_LOCK_TTL_MS = 15 * 1000;
export const STUDY_AUDIO_LOCK_POLL_INTERVAL_MS = 250;
export const STUDY_REVIEW_RAW_PAYLOAD_MAX_BYTES = 4 * 1024;
export const STUDY_IMPORT_WARNING_LIMIT = 10;
export const STUDY_IMPORT_STALE_JOB_MAX_AGE_MS = 60 * 60 * 1000;
export const STUDY_EXPORT_SECTION_LIMIT_DEFAULT = STUDY_EXPORT_PAGE_SIZE_DEFAULT;
export const STUDY_EXPORT_SECTION_LIMIT_MAX = STUDY_EXPORT_PAGE_SIZE_MAX;
