export const STUDY_GENERATED_IMPORT_JOB_ID = 'generated';
export const STUDY_MEDIA_SIGNED_URL_TTL_SECONDS = 5 * 60;
export const STUDY_MEDIA_SIGNED_URL_REFRESH_WINDOW_MS = 30 * 1000;
export const STUDY_MEDIA_REDIRECT_CACHE_MAX_ENTRIES = 1000;
