export const STUDY_CARD_NOTES_GUIDANCE = `For answer.notes, write concise learner-facing analysis of how the Japanese sentence works.
- Focus on understanding the sentence, not a full grammar lecture.
- Use only the most useful 2-5 insights for this specific card. If the sentence is very simple, 1-2 bullets is enough.
- Prefer bullet points inside the notes string. Do not add a heading.
- Cover sentence chunks, particle functions, modifiers or relative clauses, verb/adjective forms, main grammar points, omitted or implied information, register/naturalness, or common contrast points only when they are genuinely useful.
- Briefly decompose conjugated forms when helpful, including dictionary form, tense, polarity, politeness, progressive/resultative, potential, passive, causative, volitional, or conditional meaning.
- Include a literal gloss only when it helps explain the Japanese structure. Keep the natural translation separate if another field already provides it.
- Use simple terminology, avoid unnecessary linguistic jargon, and do not over-explain every word.
- Do not include romaji.
- Keep notes compact enough for the back side of a flashcard.
- If meaning is ambiguous, say "likely" or "depending on context."`;
