export type JLPTLevel = 'N5' | 'N4';
export type VerbGroup = '1' | '2' | '3';

export interface VerbDictionaryEntry {
  id: string;
  dictionary: string;
  reading: string;
  meaning: string;
  jlptLevel: JLPTLevel;
  group: VerbGroup;
}

export const VERB_DATASET: VerbDictionaryEntry[] = [
  {
    id: 'au',
    dictionary: '会う',
    reading: 'あう',
    meaning: 'to meet',
    jlptLevel: 'N5',
    group: '1',
  },
  {
    id: 'iku',
    dictionary: '行く',
    reading: 'いく',
    meaning: 'to go',
    jlptLevel: 'N5',
    group: '1',
  },
  {
    id: 'kiku',
    dictionary: '聞く',
    reading: 'きく',
    meaning: 'to listen; to ask',
    jlptLevel: 'N5',
    group: '1',
  },
  {
    id: 'kaku',
    dictionary: '書く',
    reading: 'かく',
    meaning: 'to write',
    jlptLevel: 'N5',
    group: '1',
  },
  {
    id: 'nomu',
    dictionary: '飲む',
    reading: 'のむ',
    meaning: 'to drink',
    jlptLevel: 'N5',
    group: '1',
  },
  {
    id: 'yomu',
    dictionary: '読む',
    reading: 'よむ',
    meaning: 'to read',
    jlptLevel: 'N5',
    group: '1',
  },
  {
    id: 'hanasu',
    dictionary: '話す',
    reading: 'はなす',
    meaning: 'to speak',
    jlptLevel: 'N5',
    group: '1',
  },
  {
    id: 'kau',
    dictionary: '買う',
    reading: 'かう',
    meaning: 'to buy',
    jlptLevel: 'N5',
    group: '1',
  },
  {
    id: 'matsu',
    dictionary: '待つ',
    reading: 'まつ',
    meaning: 'to wait',
    jlptLevel: 'N5',
    group: '1',
  },
  {
    id: 'tatsu',
    dictionary: '立つ',
    reading: 'たつ',
    meaning: 'to stand up',
    jlptLevel: 'N5',
    group: '1',
  },
  {
    id: 'isogu',
    dictionary: '急ぐ',
    reading: 'いそぐ',
    meaning: 'to hurry',
    jlptLevel: 'N5',
    group: '1',
  },
  {
    id: 'asobu',
    dictionary: '遊ぶ',
    reading: 'あそぶ',
    meaning: 'to play; to hang out',
    jlptLevel: 'N5',
    group: '1',
  },
  {
    id: 'taberu',
    dictionary: '食べる',
    reading: 'たべる',
    meaning: 'to eat',
    jlptLevel: 'N5',
    group: '2',
  },
  {
    id: 'miru',
    dictionary: '見る',
    reading: 'みる',
    meaning: 'to see; to watch',
    jlptLevel: 'N5',
    group: '2',
  },
  {
    id: 'akeru',
    dictionary: '開ける',
    reading: 'あける',
    meaning: 'to open (something)',
    jlptLevel: 'N5',
    group: '2',
  },
  {
    id: 'shimeru',
    dictionary: '閉める',
    reading: 'しめる',
    meaning: 'to close (something)',
    jlptLevel: 'N5',
    group: '2',
  },
  {
    id: 'okiru',
    dictionary: '起きる',
    reading: 'おきる',
    meaning: 'to wake up',
    jlptLevel: 'N5',
    group: '2',
  },
  {
    id: 'neru',
    dictionary: '寝る',
    reading: 'ねる',
    meaning: 'to sleep',
    jlptLevel: 'N5',
    group: '2',
  },
  {
    id: 'oshieru',
    dictionary: '教える',
    reading: 'おしえる',
    meaning: 'to teach',
    jlptLevel: 'N5',
    group: '2',
  },
  {
    id: 'kariru',
    dictionary: '借りる',
    reading: 'かりる',
    meaning: 'to borrow',
    jlptLevel: 'N5',
    group: '2',
  },
  {
    id: 'kiru',
    dictionary: '着る',
    reading: 'きる',
    meaning: 'to wear',
    jlptLevel: 'N5',
    group: '2',
  },
  {
    id: 'suru',
    dictionary: 'する',
    reading: 'する',
    meaning: 'to do',
    jlptLevel: 'N5',
    group: '3',
  },
  {
    id: 'kuru',
    dictionary: '来る',
    reading: 'くる',
    meaning: 'to come',
    jlptLevel: 'N5',
    group: '3',
  },
  {
    id: 'motsu',
    dictionary: '持つ',
    reading: 'もつ',
    meaning: 'to hold; to carry',
    jlptLevel: 'N4',
    group: '1',
  },
  {
    id: 'tsukuru',
    dictionary: '作る',
    reading: 'つくる',
    meaning: 'to make; to build',
    jlptLevel: 'N4',
    group: '1',
  },
  {
    id: 'hashiru',
    dictionary: '走る',
    reading: 'はしる',
    meaning: 'to run',
    jlptLevel: 'N4',
    group: '1',
  },
  {
    id: 'omu',
    dictionary: '思う',
    reading: 'おもう',
    meaning: 'to think',
    jlptLevel: 'N4',
    group: '1',
  },
  {
    id: 'warau',
    dictionary: '笑う',
    reading: 'わらう',
    meaning: 'to laugh; to smile',
    jlptLevel: 'N4',
    group: '1',
  },
  {
    id: 'kaesu',
    dictionary: '返す',
    reading: 'かえす',
    meaning: 'to return (something)',
    jlptLevel: 'N4',
    group: '1',
  },
  {
    id: 'arau',
    dictionary: '洗う',
    reading: 'あらう',
    meaning: 'to wash',
    jlptLevel: 'N4',
    group: '1',
  },
  {
    id: 'tsukau',
    dictionary: '使う',
    reading: 'つかう',
    meaning: 'to use',
    jlptLevel: 'N4',
    group: '1',
  },
  {
    id: 'kaeru-g1',
    dictionary: '帰る',
    reading: 'かえる',
    meaning: 'to return home',
    jlptLevel: 'N4',
    group: '1',
  },
  {
    id: 'kimeru',
    dictionary: '決める',
    reading: 'きめる',
    meaning: 'to decide',
    jlptLevel: 'N4',
    group: '2',
  },
  {
    id: 'kaeru-g2',
    dictionary: '変える',
    reading: 'かえる',
    meaning: 'to change (something)',
    jlptLevel: 'N4',
    group: '2',
  },
  {
    id: 'shiraberu',
    dictionary: '調べる',
    reading: 'しらべる',
    meaning: 'to investigate; to check',
    jlptLevel: 'N4',
    group: '2',
  },
  {
    id: 'tsuzukeru',
    dictionary: '続ける',
    reading: 'つづける',
    meaning: 'to continue',
    jlptLevel: 'N4',
    group: '2',
  },
  {
    id: 'uketoru',
    dictionary: '受ける',
    reading: 'うける',
    meaning: 'to receive; to take (a test)',
    jlptLevel: 'N4',
    group: '2',
  },
  {
    id: 'yameru',
    dictionary: 'やめる',
    reading: 'やめる',
    meaning: 'to stop; to quit',
    jlptLevel: 'N4',
    group: '2',
  },
  {
    id: 'dekiru',
    dictionary: 'できる',
    reading: 'できる',
    meaning: 'to be able to; to be made',
    jlptLevel: 'N4',
    group: '2',
  },
  {
    id: 'shinjiru',
    dictionary: '信じる',
    reading: 'しんじる',
    meaning: 'to believe',
    jlptLevel: 'N4',
    group: '2',
  },
  {
    id: 'benkyou-suru',
    dictionary: '勉強する',
    reading: 'べんきょうする',
    meaning: 'to study',
    jlptLevel: 'N4',
    group: '3',
  },
  {
    id: 'ryokou-suru',
    dictionary: '旅行する',
    reading: 'りょこうする',
    meaning: 'to travel',
    jlptLevel: 'N4',
    group: '3',
  },
];
