import { prisma } from '../src/db/client.js';
import { courseQueue } from '../src/jobs/courseQueue.js';

async function retryCourse() {
  // Reset the course to draft status
  const course = await prisma.course.update({
    where: { id: 'd1f97e61-dcb6-4acf-8646-1e57835c0861' },
    data: { status: 'draft' },
  });

  console.log(`✓ Reset course to draft status`);

  // Queue generation job
  const job = await courseQueue.add('generate-course', {
    courseId: course.id,
  });

  console.log(`✓ Queued job: ${job.id}`);
  console.log(`  Course will be generated by worker`);
  console.log(`\nℹ️  Monitor worker logs to see generation progress`);

  await courseQueue.close();
  await prisma.$disconnect();
}

retryCourse();
