export const MAX_STUDY_IMPORT_BYTES = 200 * 1024 * 1024;
export const MAX_STUDY_ASYNC_IMPORT_BYTES = 2 * 1024 * 1024 * 1024;
export const STUDY_IMPORT_UPLOAD_SESSION_TTL_MS = 60 * 60 * 1000;

export const STUDY_BROWSER_PAGE_SIZE_DEFAULT = 100;
export const STUDY_BROWSER_PAGE_SIZE_MAX = 100;

export const STUDY_EXPORT_PAGE_SIZE_DEFAULT = 500;
export const STUDY_EXPORT_PAGE_SIZE_MAX = 1000;

export const STUDY_NEW_CARDS_PER_DAY_DEFAULT = 20;
export const STUDY_NEW_CARDS_PER_DAY_MAX = 1000;
export const STUDY_NEW_CARD_QUEUE_PAGE_SIZE_DEFAULT = 100;
export const STUDY_NEW_CARD_QUEUE_PAGE_SIZE_MAX = 500;

export const STUDY_CANDIDATE_TARGET_MAX_LENGTH = 500;
export const STUDY_CANDIDATE_CONTEXT_MAX_LENGTH = 2000;
export const STUDY_CANDIDATE_COMMIT_MAX_COUNT = 10;
