export const MAX_STUDY_IMPORT_BYTES = 200 * 1024 * 1024;

export const STUDY_BROWSER_PAGE_SIZE_DEFAULT = 100;
export const STUDY_BROWSER_PAGE_SIZE_MAX = 100;

export const STUDY_HISTORY_PAGE_SIZE_DEFAULT = 50;
export const STUDY_HISTORY_PAGE_SIZE_MAX = 100;

export const STUDY_EXPORT_PAGE_SIZE_DEFAULT = 500;
export const STUDY_EXPORT_PAGE_SIZE_MAX = 1000;
